version: '3.0'
services:
  pg:
    container_name: postgres_minders
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secure
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minders
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - pg
    environment:
      PG_PASSWORD: secure
      PG_USER: postgres
      PG_HOST: postgres_minders
